default_platform(:android)

platform :android do
  desc "Build Android Release AAB"
  lane :build do
    gradle(
      task: "bundle",
      build_type: "Release"
    )
  end

  desc "Upload to Play Store"
  lane :deploy do
    supply(
      aab: "app/build/outputs/bundle/release/app-release.aab",
      track: "internal"
    )
  end
end
