default_platform(:ios)

platform :ios do
  desc "Build iOS IPA"
  lane :build do
    gym(
      workspace: Dir["*.xcworkspace"].first,
      scheme: Dir["*.xcodeproj"].map { |f| File.basename(f, ".xcodeproj") }.first,
      export_method: "app-store"
    )
  end

  desc "Upload to TestFlight"
  lane :deploy do
    pilot
  end
end
